RES_WIDTH = 800
RES_HEIGHT = 600
GAME_BORDER_THICKNESS = 3
GAME_BORDER_PADDING_X = 43
GAME_BORDER_PADDING_Y = 43
GAME_BORDER_WIDTH = RES_WIDTH - GAME_BORDER_PADDING_X - GAME_BORDER_PADDING_X
GAME_BORDER_HEIGHT = RES_HEIGHT - GAME_BORDER_PADDING_Y - GAME_BORDER_PADDING_Y
